Exit-guard implementado en distintos componentes
SBellido/AppsWebBio pull request #117
Opened 2022-03-11 18:20 UTC by nahurup

2022-03-14 21:36 UTC, jimartinezabadias requested changes

2022-03-14 21:36 UTC, jimartinezabadias commented on src/app/encode/encode-routing.module.ts
> +                canDeactivate: [ExitGuard],
Vamos a esperar a preguntarle a Matias antes de implementar on-exit en esta parte.
Por ahora no lo implementes en los Google Forms.

2022-03-14 21:36 UTC, jimartinezabadias commented on src/app/encode/google-forms-component/encode-google-forms.component.ts
> +  onExit(): boolean | UrlTree | Observable<boolean | UrlTree> | Promise<boolean | UrlTree> {
No implementar (dejar como estaba)

2022-03-14 21:36 UTC, jimartinezabadias commented on src/app/encode/identification-task-component/identification-task.component.ts
> +    this._userService.user.sessionTwo.completed = true;
- No marcar "completed = true". Si abandona la sesión actual tiene que quedar con "completed = false".
- Revisar todos los componentes (sesión 1 y 2) y aplicar el mismo criterio.

2022-03-15 12:14 UTC, jimartinezabadias requested changes
Joya todos los cambios.

Veo que estamos repitiendo la función _abandonTest en muchos componentes, fijate si la podes llevar al userService.

2022-03-15 12:52 UTC, nahurup commented
> _abandonTest

Listo

2022-03-15 13:45 UTC, jimartinezabadias requested changes
Habría que hacer un par de cositas:

- No usar en router en el userService, solamente guardan como abandonado.
- Cada componente devuelve la dirección "/" usando un UrlTree.

Si no se entiende no pasa nada, dsp lo vemos juntos.

2022-03-15 13:45 UTC, jimartinezabadias commented on src/app/encode/services/EncodeUserService.ts
> +    constructor(private _dbService: DataDbService, private _http: HttpClient, private _router: Router)
No inyectar router acá.

2022-03-15 13:45 UTC, jimartinezabadias commented on src/app/encode/services/EncodeUserService.ts
> +    public async abandonTest() {
Cambiar por:

```suggestion
    public abandonTest(): Promise<void> {
        this._user.abandonedByUser = true;
        return this.updateUserInDB();
    }
```

fijate que va sin el navigate.

2022-03-15 13:45 UTC, jimartinezabadias commented on src/app/encode/sorting-task-component/sorting-task.component.ts
> +    return exitDialogRef.afterClosed().toPromise<boolean>();
Cambiar a:

```suggestion
    return exitDialogRef.afterClosed().toPromise<boolean | UrlTree>();
```

2022-03-15 13:45 UTC, jimartinezabadias commented on src/app/encode/sorting-task-component/sorting-task.component.ts
> +  private _exitDialogClosed$ = async (response: boolean): Promise<boolean> => {
Cambiar por:

```suggestion
  private _exitDialogClosed$ = async (response: boolean): Promise<boolean | UrlTree> => {
```

2022-03-15 13:45 UTC, jimartinezabadias commented on src/app/encode/sorting-task-component/sorting-task.component.ts
> +      return true;
Probar, creo que devolviendo el UrlTree te navega
```suggestion
      return true;
```

```suggestion
      const redirectUrl: UrlTree = this._router.parseUrl('/');
      return redirectUrl;
```

[UrlTree Angular Docs](https://angular.io/api/router/UrlTree)

2022-03-15 13:45 UTC, jimartinezabadias commented on src/app/encode/sorting-task-component/sorting-task.component.ts
> +      this._userService.abandonTest();
```suggestion
      await this._userService.abandonTest();
```

2022-03-17 17:41 UTC, jimartinezabadias requested changes
Joya, hay que acomodar dos cositas y queda listo:

- Sacar el constructor del exit guard.
- Sacar UrlTree en la arrow function _exitDialogClosed$

2022-03-18 21:13 UTC, jimartinezabadias approved these changes

2022-03-18 21:13 UTC, merged